package api

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"
	"time"

	"buildgate/internal/daemonheartbeat"
	"buildgate/internal/progress"
	"buildgate/internal/release"
	"buildgate/internal/request"
	"buildgate/internal/run"
)

// contractFixtureDir holds one file per API read route, generated by
// TestConsoleContractFixtures from a fixed data directory and decoded by the
// console's own tests. The console's types are written by hand, so this is
// what fails when a Go field is added, renamed or retyped: the fixture goes
// stale here, and the regenerated one either still decodes there or does
// not.
//
// Regenerate with:
//
//	FACTORYD_UPDATE_GOLDEN=1 go test ./internal/api -run TestConsoleContractFixtures
const contractFixtureDir = "../../console/test/fixtures/api"

// contractFixtureTime is the instant every seeded record is stamped with or
// offset from. It is far enough in the past that every time-dependent view
// field (a stale worker heartbeat, a stalled run) has settled.
const contractFixtureTime = "2026-09-10T09:00:00Z"

// contractRoute is one fixture: Pattern is the mux pattern it covers (so
// TestConsoleContractFixtures can refuse a read route with no fixture),
// Path the concrete request, File the fixture's name. Events > 0 marks a
// server-sent-event stream that never ends by itself: the fixture is its
// first Events events.
type contractRoute struct {
	Pattern string `json:"pattern"`
	Path    string `json:"path"`
	File    string `json:"file"`
	Status  int    `json:"status"`
	// ContentType is the response's media type without parameters; the
	// console picks a JSON decoder, a text reader or an SSE parser by it.
	ContentType string `json:"content_type"`
	Events      int    `json:"-"`
}

func contractRoutes() []contractRoute {
	return []contractRoute{
		{Pattern: "GET /healthz", Path: "/healthz", File: "healthz.json"},
		{Pattern: "GET /console-config.json", Path: "/console-config.json", File: "console-config.json"},
		{Pattern: "GET /projects", Path: "/projects", File: "projects.json"},
		{Pattern: "GET /projects/{project}/release", Path: "/projects/app/release", File: "project-release.json"},
		{Pattern: "GET /projects/{project}/stats", Path: "/projects/app/stats", File: "project-stats.json"},
		{Pattern: "GET /queue-run", Path: "/queue-run", File: "queue-run.json"},
		{Pattern: "GET /daemons", Path: "/daemons", File: "daemons.json"},
		{Pattern: "GET /workspaces", Path: "/workspaces", File: "workspaces.json"},
		{Pattern: "GET /runs", Path: "/runs", File: "runs.json"},
		{Pattern: "GET /runs/{id}", Path: "/runs/run-accepted", File: "run-accepted.json"},
		{Pattern: "GET /runs/{id}", Path: "/runs/run-quarantined", File: "run-quarantined.json"},
		{Pattern: "GET /runs/{id}", Path: "/runs/run-running", File: "run-running.json"},
		{Pattern: "GET /runs/{id}", Path: "/runs/run-every-field", File: "run-every-field.json"},
		{Pattern: "GET /runs/{id}", Path: "/runs/run-missing", File: "error-not-found.json"},
		{Pattern: "GET /runs/{id}/events", Path: "/runs/run-accepted/events", File: "run-events.sse"},
		{Pattern: "GET /runs/{id}/progress", Path: "/runs/run-accepted/progress", File: "run-progress.sse"},
		{Pattern: "GET /runs/{id}/log", Path: "/runs/run-accepted/log", File: "run-log.txt"},
		{Pattern: "GET /runs/{id}/diff", Path: "/runs/run-accepted/diff", File: "run-diff.json"},
		{Pattern: "GET /runs/{id}/release", Path: "/runs/run-accepted/release", File: "run-release.json"},
		{Pattern: "GET /runs/{id}/release", Path: "/runs/run-quarantined/release", File: "run-release-no-decision.json"},
		{Pattern: "GET /requests", Path: "/requests", File: "requests.json"},
		{Pattern: "GET /requests/events", Path: "/requests/events", File: "request-events.sse", Events: len(contractRequestIDs)},
		{Pattern: "GET /requests/{id}", Path: "/requests/req-spec-review", File: "request-spec-review.json"},
		{Pattern: "GET /requests/{id}", Path: "/requests/req-oracle-review", File: "request-oracle-review.json"},
		{Pattern: "GET /requests/{id}", Path: "/requests/req-plan-review", File: "request-plan-review.json"},
		{Pattern: "GET /requests/{id}", Path: "/requests/req-building", File: "request-building.json"},
		{Pattern: "GET /requests/{id}", Path: "/requests/req-done", File: "request-done.json"},
		{Pattern: "GET /requests/{id}", Path: "/requests/req-quarantined", File: "request-quarantined.json"},
		{Pattern: "GET /requests/{id}", Path: "/requests/req-halted", File: "request-halted.json"},
		{Pattern: "GET /requests/{id}", Path: "/requests/req-every-field", File: "request-every-field.json"},
		{Pattern: "GET /requests/{id}/oracle", Path: "/requests/req-oracle-review/oracle", File: "request-oracle.json"},
		{Pattern: "GET /requests/{id}/oracle/{name}", Path: "/requests/req-oracle-review/oracle/RUN_COMMAND.txt", File: "request-oracle-file.txt"},
		{Pattern: "GET /requests/{id}/tickets/{n}/oracle", Path: "/requests/req-plan-review/tickets/1/oracle", File: "ticket-oracle.json"},
		{Pattern: "GET /requests/{id}/tickets/{n}/oracle/{name}", Path: "/requests/req-plan-review/tickets/1/oracle/RUN_COMMAND.txt", File: "ticket-oracle-file.txt"},
		{Pattern: "GET /requests/{id}/revisions", Path: "/requests/req-plan-review/revisions", File: "request-revisions.json"},
		{Pattern: "GET /requests/{id}/revisions/{n}", Path: "/requests/req-plan-review/revisions/1", File: "request-revision.json"},
	}
}

// contractRequestIDs is every seeded request, so the request event stream's
// fixture knows how many events its first snapshot holds.
var contractRequestIDs = []string{"req-building", "req-done", "req-every-field", "req-halted", "req-oracle-review", "req-plan-review", "req-quarantined", "req-spec-review"}

// TestConsoleContractFixtures serves every read route from a fixed data
// directory and compares the response with its committed fixture.
func TestConsoleContractFixtures(t *testing.T) {
	dataDir := t.TempDir()
	workspace := t.TempDir()
	seedContractFixtureData(t, dataDir, workspace)

	server := httptest.NewServer(NewServer(dataDir,
		WithWorkspaces([]string{workspace}),
		WithTemporalUIURL("http://localhost:8233"),
		WithDaemonController(&daemonControllerStub{statuses: []DaemonStatus{{
			Repository: "acme/app", State: "running", PID: 4242,
			StartedAt: contractFixtureTime, HeartbeatUpdatedAt: contractFixtureTime,
		}}}),
		WithProjectStatsProvider(func(_ context.Context, project string) (ProjectStats, error) {
			var stats ProjectStats
			fillEveryField(reflect.ValueOf(&stats).Elem(), "")
			stats.Project = project
			return stats, nil
		}),
		WithStartToken("contract-token"),
	))
	defer server.Close()

	// A real path is replaced by a fixed one, longest first, so a fixture
	// is the same on every machine. macOS reports a temp dir under both
	// /var and /private/var.
	replacements := []string{}
	for from, to := range map[string]string{dataDir: "/data", workspace: "/repos/app"} {
		replacements = append(replacements, "/private"+from, to, from, to)
		if resolved, err := filepath.EvalSymlinks(from); err == nil {
			replacements = append(replacements, resolved, to)
		}
	}
	normalize := strings.NewReplacer(replacements...)

	routes := contractRoutes()
	covered := map[string]bool{}
	files := map[string]bool{"index.json": true}
	update := os.Getenv("FACTORYD_UPDATE_GOLDEN") == "1"
	if update {
		if err := os.MkdirAll(contractFixtureDir, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	check := func(name string, got []byte) {
		t.Helper()
		files[name] = true
		path := filepath.Join(contractFixtureDir, name)
		if update {
			if err := os.WriteFile(path, got, 0o644); err != nil {
				t.Fatal(err)
			}
			return
		}
		want, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("%s: %v (regenerate: FACTORYD_UPDATE_GOLDEN=1 go test ./internal/api -run TestConsoleContractFixtures)", name, err)
			return
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s is stale: the API's response changed. Regenerate with FACTORYD_UPDATE_GOLDEN=1 go test ./internal/api -run TestConsoleContractFixtures, then run the console's tests: its decoders read these files.\n--- got ---\n%s", name, got)
		}
	}

	for i := range routes {
		route := &routes[i]
		covered[route.Pattern] = true
		req, err := http.NewRequest(http.MethodGet, server.URL+route.Path, nil)
		if err != nil {
			t.Fatal(err)
		}
		req.Header.Set("Authorization", "Bearer contract-token")
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		resp, err := http.DefaultClient.Do(req.WithContext(ctx))
		if err != nil {
			cancel()
			t.Fatalf("GET %s: %v", route.Path, err)
		}
		var body []byte
		if route.Events > 0 {
			body, err = readSSEEvents(resp.Body, route.Events)
		} else {
			body, err = io.ReadAll(resp.Body)
		}
		resp.Body.Close()
		cancel()
		if err != nil {
			t.Fatalf("GET %s: read body: %v", route.Path, err)
		}
		route.Status = resp.StatusCode
		route.ContentType, _, _ = strings.Cut(resp.Header.Get("Content-Type"), ";")

		body = []byte(normalize.Replace(string(body)))
		// How long a run has been silent is measured from the wall clock.
		body = stalledSince.ReplaceAll(body, []byte(`"stalled_since_seconds":86400`))
		if route.ContentType == "application/json" {
			var indented bytes.Buffer
			if err := json.Indent(&indented, body, "", "  "); err != nil {
				t.Fatalf("GET %s: body is not JSON: %v\n%s", route.Path, err, body)
			}
			body = append(bytes.TrimRight(indented.Bytes(), "\n"), '\n')
		}
		if wantJSON := strings.HasSuffix(route.File, ".json"); wantJSON != (route.ContentType == "application/json") {
			t.Errorf("GET %s: content type %q does not match fixture name %s", route.Path, route.ContentType, route.File)
		}
		check(route.File, body)
	}

	index, err := json.MarshalIndent(routes, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	check("index.json", append(index, '\n'))

	// Every read route the server registers has a fixture, and every file
	// in the directory is one this test wrote.
	source, err := os.ReadFile("server.go")
	if err != nil {
		t.Fatal(err)
	}
	registered := regexp.MustCompile(`s\.mux\.HandleFunc\("(GET /[^"]*)"`).FindAllSubmatch(source, -1)
	if len(registered) < 20 {
		t.Fatalf("found only %d GET routes in server.go; the route scan no longer matches how routes are registered", len(registered))
	}
	for _, m := range registered {
		if pattern := string(m[1]); !covered[pattern] {
			t.Errorf("%s has no contract fixture: add it to contractRoutes", pattern)
		}
	}
	entries, err := os.ReadDir(contractFixtureDir)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if !files[entry.Name()] {
			t.Errorf("%s/%s is not written by this test: delete it", contractFixtureDir, entry.Name())
		}
	}
}

var stalledSince = regexp.MustCompile(`"stalled_since_seconds":\s*\d+`)

// readSSEEvents reads the first n events (blank-line-terminated blocks) of
// a stream that never ends.
func readSSEEvents(r io.Reader, n int) ([]byte, error) {
	var out bytes.Buffer
	reader := bufio.NewReader(r)
	for n > 0 {
		line, err := reader.ReadString('\n')
		out.WriteString(line)
		if err != nil {
			return out.Bytes(), err
		}
		if line == "\n" {
			n--
		}
	}
	return out.Bytes(), nil
}

// fillEveryField sets every exported field under v to a fixed non-zero
// value, so a fixture built from it carries every field the API can send,
// including one added after this test was written. Named string types
// (states, kinds) are left for the caller: only it knows a valid value.
func fillEveryField(v reflect.Value, jsonName string) {
	switch v.Kind() {
	case reflect.String:
		switch {
		case v.Type().PkgPath() != "":
		case jsonName == "at" || jsonName == "ts" || jsonName == "generated" || strings.HasSuffix(jsonName, "_at") || strings.HasSuffix(jsonName, "_since"):
			v.SetString(contractFixtureTime)
		default:
			v.SetString("every-field " + jsonName)
		}
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int64:
		v.SetInt(3)
	case reflect.Float64:
		v.SetFloat(1.5)
	case reflect.Pointer:
		v.Set(reflect.New(v.Type().Elem()))
		fillEveryField(v.Elem(), jsonName)
	case reflect.Slice:
		v.Set(reflect.MakeSlice(v.Type(), 1, 1))
		fillEveryField(v.Index(0), jsonName)
	case reflect.Map:
		v.Set(reflect.MakeMap(v.Type()))
		elem := reflect.New(v.Type().Elem()).Elem()
		if elem.Kind() == reflect.Interface {
			// A usage map as build_app.py's parse_usage writes it.
			v.SetMapIndex(reflect.ValueOf("input"), reflect.ValueOf(100))
			v.SetMapIndex(reflect.ValueOf("output"), reflect.ValueOf(50))
			v.SetMapIndex(reflect.ValueOf("totalTokens"), reflect.ValueOf(150))
			return
		}
		fillEveryField(elem, jsonName)
		v.SetMapIndex(reflect.ValueOf("every-field key"), elem)
	case reflect.Struct:
		if v.Type() == reflect.TypeOf(time.Time{}) {
			at, _ := time.Parse(time.RFC3339, contractFixtureTime)
			v.Set(reflect.ValueOf(at))
			return
		}
		for i := 0; i < v.NumField(); i++ {
			field := v.Type().Field(i)
			if !field.IsExported() {
				continue
			}
			name, _, _ := strings.Cut(field.Tag.Get("json"), ",")
			fillEveryField(v.Field(i), name)
		}
	default:
		panic(fmt.Sprintf("fillEveryField: no fixed value for %s field %q", v.Kind(), jsonName))
	}
}

const contractSpec = `# Idempotency keys for checkout

## Problem

A retried checkout charges the card twice.

## Acceptance criteria

1. A repeated request with the same key returns the first response.
2. A key is scoped to one account.
`

const contractOracleRunCommand = "go test ./.oracle/...\n"

// contractOracleTest is a test file the oracle checks accept: a Go test
// declaring a TestOracle function.
const contractOracleTest = "package oracle\n\nimport \"testing\"\n\nfunc TestOracleIdempotency(t *testing.T) {}\n"

// seedContractFixtureData writes the data directory the fixtures are
// served from: one request in each state the console draws differently,
// the runs behind them, and one request and one run with every field set.
func seedContractFixtureData(t *testing.T, dataDir, workspace string) {
	t.Helper()
	at, err := time.Parse(time.RFC3339, contractFixtureTime)
	if err != nil {
		t.Fatal(err)
	}
	stamp := func(minutes int) string { return at.Add(time.Duration(minutes) * time.Minute).Format(time.RFC3339) }
	must := func(err error) {
		t.Helper()
		if err != nil {
			t.Fatal(err)
		}
	}
	write := func(path, content string) {
		t.Helper()
		must(os.MkdirAll(filepath.Dir(path), 0o750))
		must(os.WriteFile(path, []byte(content), 0o600))
	}
	usage := func(total int) map[string]any {
		return map[string]any{"input": total - 50, "output": 50, "totalTokens": total}
	}

	// A request is written as its JSON, not through Request.Save: Save
	// appends a history entry stamped with the wall clock for a state the
	// record was not loaded in.
	saveRequest := func(r *request.Request) {
		t.Helper()
		b, err := json.MarshalIndent(r, "", "  ")
		must(err)
		write(request.Path(dataDir, r.ID), string(b))
	}
	newRequest := func(id string, state request.State) *request.Request {
		must(request.SaveText(dataDir, id, "Add idempotency keys to checkout\n\nA retried checkout charges the card twice.\n"))
		r := request.New(id, workspace, "app", request.Source{Kind: request.SourceText}, at)
		r.State = state
		r.UpdatedAt, r.EnteredAt = stamp(5), stamp(5)
		r.History = []request.Transition{
			{From: request.StateSubmitted, To: request.StateSpecDrafting, At: stamp(0), By: "factoryd"},
			{From: request.StateSpecDrafting, To: request.StateSpecReview, At: stamp(5), By: "factoryd", Reason: "spec drafted"},
		}
		r.SpecEvidence = &request.SpecEvidence{
			Usage: usage(1200), DurationS: 41.5, AgentsMDUsed: true, Model: "gpt-5.6-luna", Thinking: "high",
			Spend: &request.JobSpend{Role: "planning", Model: "gpt-5.6-luna", InputTokens: 1150, OutputTokens: 50, CostMicroUSD: 12000, At: at},
		}
		write(filepath.Join(request.Dir(dataDir, id), "spec.md"), contractSpec)
		return r
	}
	ticketPath := func(id string, n int) string {
		return filepath.Join(request.Dir(dataDir, id), "tickets", fmt.Sprintf("%03d.spec.md", n))
	}
	writeTickets := func(id string, count int) {
		for n := 1; n <= count; n++ {
			write(ticketPath(id, n), seedApprovableRequestTicket)
		}
	}

	specReview := newRequest("req-spec-review", request.StateSpecReview)
	specReview.WaitingSince = stamp(5)
	saveRequest(specReview)

	oracleReview := newRequest("req-oracle-review", request.StateOracleReview)
	oracleReview.Source = request.Source{Kind: request.SourceIssue, IssueRef: "acme/app#42"}
	oracleReview.DraftOracles = true
	oracleReview.WaitingSince = stamp(9)
	oracleReview.OracleDraft = &request.OracleDraft{
		Status: "drafted", Detail: "one criterion is covered", ProposedCommand: "go test ./.oracle/...",
		Files:    []string{"idempotency_test.go"},
		Criteria: []request.OracleCriterionVerdict{{Number: 1, Eligible: true}, {Number: 2, Eligible: false, Reason: "needs a second account"}},
		Model:    "gpt-5.6-luna", Thinking: "high",
	}
	write(filepath.Join(request.Dir(dataDir, oracleReview.ID), "oracle", "RUN_COMMAND.txt"), contractOracleRunCommand)
	write(filepath.Join(request.Dir(dataDir, oracleReview.ID), "oracle", "idempotency_test.go"), contractOracleTest)
	write(filepath.Join(request.Dir(dataDir, oracleReview.ID), "oracle", "MANIFEST.json"),
		`[{"criterion": "A repeated request with the same key returns the first response.", "oracle_file": "idempotency_test.go", "criterion_index": 1}]`+"\n")
	saveRequest(oracleReview)

	planReview := newRequest("req-plan-review", request.StatePlanReview)
	planReview.TicketCount = 2
	planReview.Tickets = []request.Ticket{{Index: 1, SpecPath: ticketPath(planReview.ID, 1)}, {Index: 2, SpecPath: ticketPath(planReview.ID, 2)}}
	planReview.ApprovedBy, planReview.ApprovedAt = "alice", stamp(6)
	planReview.PlanEvidence = &request.PlanEvidence{Usage: usage(900), DurationS: 30, Model: "gpt-5.6-luna"}
	// A re-review: the plan was rejected once with a note on ticket 1's
	// steps, and the ticket on disk is the redraft. The revision below holds
	// the rejected text, so the console has a section that changed to show.
	planAnchors := []request.RejectionAnchor{{Path: "tickets/001.spec.md", Section: "### Steps", Note: "split the migration out"}}
	planReason := request.AnchoredReason(planAnchors, "Otherwise fine.")
	planReview.Rejections = []request.Rejection{{By: "alice", At: stamp(8), Reason: planReason, FromState: request.StatePlanReview, Anchors: planAnchors, Note: "Otherwise fine."}}
	writeTickets(planReview.ID, 2)
	write(ticketPath(planReview.ID, 1), strings.Replace(seedApprovableRequestTicket, "1. s\n", "1. migrate and switch over in one step\n", 1))
	write(filepath.Join(request.Dir(dataDir, planReview.ID), "tickets", "001.oracle", "RUN_COMMAND.txt"), contractOracleRunCommand)
	write(filepath.Join(request.Dir(dataDir, planReview.ID), "tickets", "001.oracle", "idempotency_test.go"), contractOracleTest)
	saveRequest(planReview)
	if _, err := request.SnapshotRevision(dataDir, planReview.ID, "alice", planReason, request.StatePlanReview,
		[]string{"spec.md", "tickets/001.spec.md", "tickets/002.spec.md"}, at.Add(8*time.Minute)); err != nil {
		t.Fatal(err)
	}
	write(ticketPath(planReview.ID, 1), seedApprovableRequestTicket)

	building := newRequest("req-building", request.StateBuilding)
	building.TicketCount, building.TicketIndex = 2, 2
	building.Models = map[string]string{"execution": "gpt-5.6-luna"}
	building.Harnesses = map[string]string{"execution": "pi"}
	building.Tickets = []request.Ticket{
		{Index: 1, SpecPath: ticketPath(building.ID, 1), RunID: "run-accepted", Branch: "factory/req-building-1", PRURL: "https://github.com/acme/app/pull/7", PRState: "open", PRBase: "main",
			Rounds: []request.Round{{Index: 1, Kind: "review", ThreadIDs: []string{"thread-1"}, RunID: "run-quarantined", Outcome: "failed", At: stamp(40), Error: "verify failed"}}},
		{Index: 2, SpecPath: ticketPath(building.ID, 2), RunID: "run-running"},
	}
	writeTickets(building.ID, 2)
	saveRequest(building)
	must(request.WriteActiveJob(dataDir, building.ID, request.ActiveJob{
		Stage: "build", Role: "execution", Model: "luna", ModelID: "gpt-5.6-luna", Harness: "pi", Thinking: "high", Route: "chatgpt-codex", StartedAt: stamp(45),
	}))

	done := newRequest("req-done", request.StateDone)
	done.TicketCount, done.TicketIndex = 1, 1
	done.Tickets = []request.Ticket{{Index: 1, SpecPath: ticketPath(done.ID, 1), RunID: "run-every-field", PRURL: "https://github.com/acme/app/pull/6", PRState: "merged"}}
	writeTickets(done.ID, 1)
	saveRequest(done)

	// A quarantined request an operator can send back, and a halted one:
	// the two states whose recovery actions the console offers.
	quarantinedRequest := newRequest("req-quarantined", request.StateQuarantined)
	quarantinedRequest.TicketCount, quarantinedRequest.TicketIndex = 1, 1
	quarantinedRequest.Tickets = []request.Ticket{{Index: 1, SpecPath: ticketPath(quarantinedRequest.ID, 1), RunID: "run-quarantined"}}
	quarantinedRequest.Error = "ticket 1 was quarantined: verify failed after 3 rounds"
	quarantinedRequest.QuarantineCheck = "verify"
	quarantinedRequest.ApprovedBy, quarantinedRequest.ApprovedAt = "alice", stamp(6)
	specSum := sha256.Sum256([]byte(contractSpec))
	quarantinedRequest.ApprovedSHA256 = map[string]string{"spec.md": hex.EncodeToString(specSum[:])}
	writeTickets(quarantinedRequest.ID, 1)
	saveRequest(quarantinedRequest)

	halted := newRequest("req-halted", request.StateHalted)
	halted.TicketCount, halted.TicketIndex = 1, 1
	halted.Tickets = []request.Ticket{{Index: 1, SpecPath: ticketPath(halted.ID, 1), RunID: "run-accepted", Branch: "factory/req-halted-1"}}
	halted.Error = "ticket 1 was accepted but its pull request could not be opened: gh: not logged in"
	halted.HaltKind = request.HaltAcceptedNoPR
	writeTickets(halted.ID, 1)
	saveRequest(halted)

	everyRequest := newRequest("req-every-field", request.StateResumeReview)
	fillEveryField(reflect.ValueOf(everyRequest).Elem(), "")
	everyRequest.ID, everyRequest.Workspace, everyRequest.Project = "req-every-field", workspace, "app"
	everyRequest.Source = request.Source{Kind: request.SourceIssue, IssueRef: "acme/app#43"}
	everyRequest.State = request.StateResumeReview
	everyRequest.History = []request.Transition{{From: request.StateBuilding, To: request.StateResumeReview, At: stamp(50), By: "factoryd", Reason: "the build was lost"}}
	everyRequest.Resume.FromState = request.StateBuilding
	everyRequest.Rejections[0].FromState, everyRequest.Rejections[0].ForStage = request.StateSpecReview, request.StateSpecDrafting
	everyRequest.OracleDraft.Status = "drafted"
	everyRequest.ApprovedSHA256 = nil
	everyRequest.TicketCount, everyRequest.TicketIndex = 1, 1
	everyRequest.Tickets[0].Index, everyRequest.Tickets[0].SpecPath = 1, ticketPath(everyRequest.ID, 1)
	everyRequest.Tickets[0].RunID = "run-quarantined"
	everyRequest.Tickets[0].Rounds[0].Outcome = "failed"
	writeTickets(everyRequest.ID, 1)
	saveRequest(everyRequest)

	runBase := func(id string, state run.State, requestID string) run.Run {
		return run.Run{
			ID: id, Ticket: "ticket-" + id, State: state, RequestID: requestID,
			ProjectPath: workspace, Project: "app", WorkspacePath: workspace, RepositoryRoot: workspace,
			SpecPath: ticketPath("req-building", 1), SpecSHA256: strings.Repeat("ab", 32),
			BaseSHA: strings.Repeat("1", 40), Branch: "factory/" + id,
			CreatedAt: stamp(10), UpdatedAt: stamp(30),
		}
	}
	passed := true

	accepted := runBase("run-accepted", run.StateAccepted, "req-building")
	accepted.ResultSHA, accepted.HaltConfirmed, accepted.CommittedByFactoryd = strings.Repeat("2", 40), true, true
	accepted.PullRequestURL = "https://github.com/acme/app/pull/7"
	accepted.ChangedFiles = []string{"checkout/idempotency.go", "checkout/idempotency_test.go"}
	accepted.DiffStat = &run.DiffStat{FilesChanged: 2, Insertions: 48, Deletions: 3}
	accepted.DiffAvailable = true
	accepted.TemporalWorkflowID, accepted.TemporalRunID = "run-run-accepted", "0199-contract"
	logPath := filepath.Join(run.Dir(dataDir, accepted.ID), "001-build_app.log")
	accepted.Attempts = []run.Attempt{{
		Kind: "build", Command: []string{"build_app.py", "--harness", "pi"}, StartedAt: stamp(10), FinishedAt: stamp(25), LogPath: logPath,
		Role: "execution", Harness: "pi", Thinking: "high", RelayRoute: "chatgpt-codex", RelayWorkerModelID: "gpt-5.6-luna",
		RelayCredentialMode: "chatgpt", RelayConsumedInputTokens: 470000, RelayConsumedOutputTokens: 8300, RelayConsumedCostMicroUSD: 1500000,
	}}
	accepted.GateResults = []run.GateResult{
		{Check: "verify", Command: []string{"go", "test", "./..."}, Passed: true, DurationMs: 4200, LogSHA256: strings.Repeat("cd", 32)},
		{Check: "lint", Command: []string{"go", "vet", "./..."}, Passed: true, DurationMs: 900, LogSHA256: strings.Repeat("ef", 32)},
	}
	model, provider := "gpt-5.6-luna", "chatgpt-codex"
	accepted.AgentEvidence = &run.AgentEvidence{
		SchemaVersion: 1, Generated: stamp(25), ReviewPolicy: "required", Provider: &provider, Model: &model, Succeeded: true, StoppedReason: "accepted",
		Rounds:         []run.AgentEvidenceRound{{Index: 1, Agent: "pi", Usage: usage(478300), ReviewerOutcome: "pass", VerifyPassed: &passed, DurationS: 840, FastCheckRan: true, FastCheckPassed: &passed, Blockers: []string{}, ChangedFiles: []string{"checkout/idempotency.go"}}},
		ReviewVerdicts: []run.ReviewVerdict{{Criterion: "1", Verdict: "met"}, {Criterion: "2", Verdict: "met", Detail: "covered by TestKeyScopedToAccount"}},
	}
	accepted.Overrides, accepted.Rescues, accepted.Notifications = []run.Override{}, []run.Rescue{}, []run.NotificationRecord{}
	seedRun(t, dataDir, accepted)
	write(logPath, "round 1: building\nround 1: verify passed\n")
	writeDiffFile(t, dataDir, accepted.ID, "diff --git a/checkout/idempotency.go b/checkout/idempotency.go\n--- a/checkout/idempotency.go\n+++ b/checkout/idempotency.go\n@@ -1,2 +1,3 @@\n package checkout\n+// Key scopes a retry to one account.\n")
	write(filepath.Join(run.Dir(dataDir, accepted.ID), "compose", "services.build.json"),
		`{"enabled": true, "services": [{"name": "redis", "alias": "redis", "port": 6379, "image": "redis:7.4", "digest": "redis@sha256:abc"}]}`)
	write(filepath.Join(run.Dir(dataDir, accepted.ID), "compose", "services.verify.json"),
		`{"enabled": false, "disabled_reason": "no compose file found in the target repository"}`)
	for _, e := range []progress.Event{
		{Ts: stamp(10), Source: "factory", Stage: "build", Event: "start", Round: 1, MaxRounds: 3},
		{Ts: stamp(24), Source: "agent", Stage: "build", Event: "round_summary", Round: 1, MaxRounds: 3, Detail: "478.3k tokens"},
		{Ts: stamp(25), Source: "factory", Stage: "build", Event: "end", Outcome: "pass"},
	} {
		appendProgress(t, dataDir, accepted.ID, e)
	}
	must(release.Engage(dataDir, "app", "operator@example.com", "incident 42", func() string { return stamp(26) }))
	must(release.SaveDecision(dataDir, release.Decision{
		RunID: accepted.ID, Project: "app", Allowed: false, Evaluated: stamp(27),
		Reasons: []string{`kill switch is engaged for project "app"`},
	}))

	quarantined := runBase("run-quarantined", run.StateQuarantined, "req-building")
	quarantined.HaltError, quarantined.HaltReasonCode = "verify failed after 3 rounds", "verify_failed"
	quarantined.Triage = "The verify command failed on TestKeyScopedToAccount in every round."
	quarantined.CreatedAt, quarantined.UpdatedAt = stamp(31), stamp(40)
	seedRun(t, dataDir, quarantined)

	running := runBase("run-running", run.StateSliceRunning, "req-building")
	running.CreatedAt, running.UpdatedAt = stamp(45), stamp(46)
	seedRun(t, dataDir, running)
	// The progress feed's own timestamp layout (milliseconds), so the stall
	// computation reads it: this run has been silent since.
	appendProgress(t, dataDir, running.ID, progress.Event{Ts: at.Add(46 * time.Minute).Format("2006-01-02T15:04:05.000Z07:00"), Source: "factory", Stage: "build", Event: "start", Round: 2, MaxRounds: 3})

	var every run.Run
	fillEveryField(reflect.ValueOf(&every).Elem(), "")
	every.ID, every.State, every.RequestID = "run-every-field", run.StateAccepted, "req-done"
	every.ProjectPath, every.Project, every.WorkspacePath, every.RepositoryRoot = workspace, "app", workspace, workspace
	every.CreatedAt, every.UpdatedAt = stamp(1), stamp(4)
	every.Attempts[0].Kind, every.Attempts[0].LogPath = "build", filepath.Join(run.Dir(dataDir, every.ID), "001-build_app.log")
	every.Attempts[0].StartedAt, every.Attempts[0].FinishedAt = stamp(1), stamp(3)
	every.Overrides[0].PriorState, every.Overrides[0].NewState = run.StateQuarantined, run.StateAccepted
	every.Rescues[0].PriorState, every.Rescues[0].NewState = run.StateQuarantined, run.StateAccepted
	every.Notifications[0].State = run.StateAccepted
	seedRun(t, dataDir, every)

	must(daemonheartbeat.Write(daemonheartbeat.WorkerPath(dataDir), daemonheartbeat.Heartbeat{
		Repository: "acme/app", TaskQueue: "factoryd", PID: 4242, StartedAt: contractFixtureTime, UpdatedAt: stamp(50),
	}))

	sort.Strings(contractRequestIDs)
	requests, err := request.List(dataDir)
	must(err)
	if len(requests) != len(contractRequestIDs) {
		t.Fatalf("seeded %d requests, contractRequestIDs names %d", len(requests), len(contractRequestIDs))
	}
}

// TestWriteContractFixtureDataDir writes the fixture data directory to
// FACTORYD_CONTRACT_FIXTURE_DIR and its workspace to
// FACTORYD_CONTRACT_FIXTURE_WORKSPACE, for a browser walk of the console
// against `factoryd serve -data-dir`: the same records the contract
// fixtures are served from. It is skipped unless both are set.
func TestWriteContractFixtureDataDir(t *testing.T) {
	dataDir := os.Getenv("FACTORYD_CONTRACT_FIXTURE_DIR")
	workspace := os.Getenv("FACTORYD_CONTRACT_FIXTURE_WORKSPACE")
	if dataDir == "" || workspace == "" {
		t.Skip("set FACTORYD_CONTRACT_FIXTURE_DIR and FACTORYD_CONTRACT_FIXTURE_WORKSPACE to write the fixture data directory")
	}
	for _, dir := range []string{dataDir, workspace} {
		if err := os.MkdirAll(dir, 0o750); err != nil {
			t.Fatal(err)
		}
	}
	seedContractFixtureData(t, dataDir, workspace)
}
