package hostcontrol

import (
	"archive/tar"
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// The gateway keeps its keys on the Docker VM's own disk, in this directory,
// so the CA and server keys never reach the host.
const (
	openShellVMDir    = "/var/lib/openshell"
	openShellVMCA     = openShellVMDir + "/tls/ca.crt"
	openShellVMCert   = openShellVMDir + "/tls/client/tls.crt"
	openShellVMKey    = openShellVMDir + "/tls/client/tls.key"
	openShellMTLSDirN = "mtls"
)

// OpenShellMTLSDir is where the client bundle (ca.crt, tls.crt, tls.key) that
// reaches the gateway is kept, under dir (OpenShellStackDir).
func OpenShellMTLSDir(dir string) string { return filepath.Join(dir, openShellMTLSDirN) }

// EnsureOpenShellCerts makes the gateway's certificates exist on the VM and
// the client bundle exist under dir/mtls. Keys are generated by the pinned
// gateway image on the VM's disk, skipped when a probe finds the CA already
// there; only the client bundle is copied to the host. An existing client key
// is never overwritten: a bundle whose CA differs from the VM's is an error.
func EnsureOpenShellCerts(dp Deps, ctx context.Context, dir string, t OpenShellTimeouts) error {
	run := dockerRunner{dp: dp, timeout: t.Stop}
	ca, err := run.read(ctx, openShellVMCA)
	if err != nil {
		if gerr := run.generate(ctx); gerr != nil {
			return fmt.Errorf("generate OpenShell certificates: %w", gerr)
		}
		if ca, err = run.read(ctx, openShellVMCA); err != nil {
			return fmt.Errorf("read generated OpenShell CA: %w", err)
		}
	}
	mtls := OpenShellMTLSDir(dir)
	if _, err := os.Stat(filepath.Join(mtls, "tls.key")); err == nil {
		have, rerr := os.ReadFile(filepath.Join(mtls, "ca.crt"))
		if rerr != nil || !bytes.Equal(have, ca) {
			return fmt.Errorf("client bundle in %s does not match the gateway's CA; remove %s and start again", mtls, mtls)
		}
		return nil
	}
	cert, err := run.read(ctx, openShellVMCert)
	if err != nil {
		return fmt.Errorf("read client certificate: %w", err)
	}
	key, err := run.read(ctx, openShellVMKey)
	if err != nil {
		return fmt.Errorf("read client key: %w", err)
	}
	return writeClientBundle(mtls, ca, cert, key)
}

// writeClientBundle writes the certificates (0644), then the key (0600,
// created exclusively): a present key therefore means a complete bundle.
func writeClientBundle(mtls string, ca, cert, key []byte) error {
	if err := os.MkdirAll(mtls, 0o700); err != nil {
		return fmt.Errorf("create %s: %w", mtls, err)
	}
	for name, content := range map[string][]byte{"ca.crt": ca, "tls.crt": cert} {
		if err := os.WriteFile(filepath.Join(mtls, name), content, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", filepath.Join(mtls, name), err)
		}
	}
	f, err := os.OpenFile(filepath.Join(mtls, "tls.key"), os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return fmt.Errorf("create client key: %w", err)
	}
	if _, err := f.Write(key); err != nil {
		f.Close()
		_ = os.Remove(f.Name())
		return fmt.Errorf("write client key: %w", err)
	}
	return f.Close()
}

// dockerRunner runs throwaway containers of the pinned gateway image with the
// VM's OpenShell directory bound.
type dockerRunner struct {
	dp      Deps
	timeout time.Duration
}

func (r dockerRunner) output(ctx context.Context, args ...string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(ctx, r.timeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, r.dp.DockerBinary(), args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, errors.New(LastLine(stderr.String()) + ": " + err.Error())
	}
	return out, nil
}

// generate runs the gateway image's certificate generator into the VM dir.
func (r dockerRunner) generate(ctx context.Context) error {
	_, err := r.output(ctx, "run", "--rm", "--user", "0", "-v", openShellVMDir+":"+openShellVMDir,
		OpenShellGatewayImage, "generate-certs",
		"--output-dir", openShellVMDir+"/tls", "--server-san", "127.0.0.1", "--server-san", "localhost")
	return err
}

// read returns the content of path on the VM's disk. The OpenShell images have
// no shell or cat, so the file is copied out of a container that is created
// with the directory bound read-only and never started.
func (r dockerRunner) read(ctx context.Context, path string) ([]byte, error) {
	created, err := r.output(ctx, "create", "--network", "none",
		"-v", openShellVMDir+":"+openShellVMDir+":ro", OpenShellGatewayImage)
	if err != nil {
		return nil, err
	}
	id := strings.TrimSpace(string(created))
	defer func() { _, _ = r.output(context.WithoutCancel(ctx), "rm", "-f", id) }()
	archive, err := r.output(ctx, "cp", id+":"+path, "-")
	if err != nil {
		return nil, err
	}
	return firstTarFile(archive)
}

// firstTarFile returns the content of the first regular file in a tar stream,
// which is what `docker cp <container>:<file> -` writes.
func firstTarFile(archive []byte) ([]byte, error) {
	reader := tar.NewReader(bytes.NewReader(archive))
	for {
		header, err := reader.Next()
		if err != nil {
			return nil, fmt.Errorf("no regular file in the copied archive: %w", err)
		}
		if header.Typeflag == tar.TypeReg {
			return io.ReadAll(reader)
		}
	}
}
